# Generated by Django 4.1.2 on 2022-10-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Good news, everyone!', max_length=50)),
                ('text', models.TextField()),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
