# Generated by Django 4.1.2 on 2022-10-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
